@startuml
class Persona {
 
    - m_nombre: string
    - m_apellidos: string
    - m_yearNacimiento: int

    + Persona()
    + Persona(nombre: string, apellidos: string, yearNacimiento: int)

    + getEdad(currentYear: int): int
    + getNombre(): string
    + setNombre(m_nombre: string): void
    + getApellidos(): string
    + setApellidos(m_apellidos: string): void
    + getYearNacimiento(): int
    + setYearNacimiento(m_yearNacimiento: int): void
}
@enduml
