@startuml
class Temperatura {

    - valorCelsius: double

    + Temperatura()
    + Temperatura(valorCelsius: double)
    + getValorCelsius(): double
    + setValorCelsius(valorCelsius: double): void
    + convertirAFahrenheit(): double
}
@enduml
